// Code generated by "stringer -type=Method -linecomment"; DO NOT EDIT.

package chess

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoMethod-0]
	_ = x[Checkmate-1]
	_ = x[Resignation-2]
	_ = x[DrawOffer-3]
	_ = x[Stalemate-4]
	_ = x[ThreefoldRepetition-5]
	_ = x[FivefoldRepetition-6]
	_ = x[FiftyMoveRule-7]
	_ = x[SeventyFiveMoveRule-8]
	_ = x[InsufficientMaterial-9]
	_ = x[InCheck-10]
}

const _Method_name = "NoMethodCheckmateResignationDrawOfferStalemateThreefoldRepetitionFivefoldRepetitionFiftyMoveRuleSeventyFiveMoveRuleInsufficientMaterialInCheck"

var _Method_index = [...]uint8{0, 8, 17, 28, 37, 46, 65, 83, 96, 115, 135, 142}

func (i Method) String() string {
	if i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
